### ISSUE TITLE
Exec format error in recompileLive.py ?

### ISSUE THREAD

**Issue by son0p** [essteban/CQenze#1]
I am on Ubuntu 14.04 with Python 2.7 I got this error

```
ff➜  CQenze : master ✘ :✹✭ ᐅ  ./icqenze Live.cqz     
./cqenze: line 3: ./lex: cannot execute binary file: Exec format error
python: can't open file 'recompileLIve.py': [Errno 2] No such file or directory
```

ChucK started but there is no sound yet

**Comment by celestebetancur** [comment]
Could be a problem with the C machine code produced by the lex file... I'll check.

**Comment by celestebetancur** [comment]
Fixed, please make pull and run configure file first. thanx
